std = "roblox"
[lints]
global_usage = "allow"
incorrect_standard_library_use = "allow" 
undefined_variable = "allow"
unscoped_variables = "allow"
deprecated = "allow"
shadowing = "allow"
parse_error = "allow"