return {

	WindowBackground = Color3.fromRGB(30, 30, 30),
	GroupboxBackground = Color3.fromRGB(35, 35, 35),
	ElementBackground = Color3.fromRGB(30, 30, 30),

	Stroke = Color3.fromRGB(20, 20, 20),
	FooterStroke = Color3.fromRGB(25, 25, 25),

	TooltipIcon = Color3.fromRGB(134, 134, 134),
	PrimaryText = Color3.fromRGB(193, 193, 193),
	SecondaryText = Color3.fromRGB(108, 108, 108),
	Header = Color3.fromRGB(245, 245, 245),

	Accent = Color3.fromRGB(143, 84, 182),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(24, 24, 24),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
