return {

	WindowBackground = Color3.fromRGB(17, 17, 27),
	GroupboxBackground = Color3.fromRGB(22, 22, 34),
	ElementBackground = Color3.fromRGB(27, 27, 42),

	Stroke = Color3.fromRGB(49, 50, 68),
	FooterStroke = Color3.fromRGB(27, 27, 42),

	TooltipIcon = Color3.fromRGB(108, 112, 134),
	PrimaryText = Color3.fromRGB(186, 194, 222),
	SecondaryText = Color3.fromRGB(147, 153, 178),
	Header = Color3.fromRGB(205, 214, 244),

	Accent = Color3.fromRGB(203, 166, 247),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(21, 21, 24),

	Bad = Color3.fromRGB(243, 139, 168),
	Mid = Color3.fromRGB(249, 226, 175),
	Good = Color3.fromRGB(166, 227, 161),
}
