return {

	WindowBackground = Color3.fromRGB(35, 38, 52),
	GroupboxBackground = Color3.fromRGB(39, 42, 57),
	ElementBackground = Color3.fromRGB(45, 49, 66),

	Stroke = Color3.fromRGB(65, 69, 89),
	FooterStroke = Color3.fromRGB(42, 45, 62),

	TooltipIcon = Color3.fromRGB(115, 121, 148),
	PrimaryText = Color3.fromRGB(181, 191, 226),
	SecondaryText = Color3.fromRGB(148, 156, 187),
	Header = Color3.fromRGB(198, 208, 245),

	Accent = Color3.fromRGB(238, 190, 190),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(21, 21, 24),

	Bad = Color3.fromRGB(231, 130, 132),
	Mid = Color3.fromRGB(242, 213, 207),
	Good = Color3.fromRGB(153, 209, 219),
}
