return {

	WindowBackground = Color3.fromRGB(24, 25, 38),
	GroupboxBackground = Color3.fromRGB(28, 30, 45),
	ElementBackground = Color3.fromRGB(33, 36, 54),

	Stroke = Color3.fromRGB(54, 58, 79),
	FooterStroke = Color3.fromRGB(31, 33, 50),

	TooltipIcon = Color3.fromRGB(110, 115, 141),
	PrimaryText = Color3.fromRGB(184, 192, 224),
	SecondaryText = Color3.fromRGB(147, 154, 183),
	Header = Color3.fromRGB(202, 211, 245),

	Accent = Color3.fromRGB(245, 189, 230),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(21, 21, 24),

	Bad = Color3.fromRGB(238, 153, 160),
	Mid = Color3.fromRGB(245, 169, 127),
	Good = Color3.fromRGB(139, 213, 202),
}
