return {

	WindowBackground = Color3.fromRGB(220, 224, 232),
	GroupboxBackground = Color3.fromRGB(230, 233, 239),
	ElementBackground = Color3.fromRGB(239, 241, 245),

	Stroke = Color3.fromRGB(204, 208, 218),
	FooterStroke = Color3.fromRGB(235, 237, 243),

	TooltipIcon = Color3.fromRGB(156, 160, 176),
	PrimaryText = Color3.fromRGB(92, 95, 119),
	SecondaryText = Color3.fromRGB(124, 127, 147),
	Header = Color3.fromRGB(76, 79, 105),

	Accent = Color3.fromRGB(114, 135, 253),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(21, 21, 24),

	Bad = Color3.fromRGB(230, 69, 83),
	Mid = Color3.fromRGB(223, 142, 29),
	Good = Color3.fromRGB(64, 160, 43),
}
