return {

	WindowBackground = Color3.fromRGB(11, 11, 15),
	GroupboxBackground = Color3.fromRGB(18, 18, 24),
	ElementBackground = Color3.fromRGB(24, 24, 28),

	Stroke = Color3.fromRGB(35, 36, 44),
	FooterStroke = Color3.fromRGB(32, 33, 41),

	TooltipIcon = Color3.fromRGB(115, 115, 129),
	PrimaryText = Color3.fromRGB(206, 206, 206),
	SecondaryText = Color3.fromRGB(169, 169, 179),
	Header = Color3.fromRGB(221, 221, 222),

	Accent = Color3.fromRGB(216, 79, 104),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(21, 21, 24),

	Bad = Color3.fromRGB(216, 79, 104),
	Mid = Color3.fromRGB(230, 180, 80),
	Good = Color3.fromRGB(100, 210, 130),
}
