return {

	WindowBackground = Color3.fromRGB(26, 26, 46),
	GroupboxBackground = Color3.fromRGB(38, 35, 53),
	ElementBackground = Color3.fromRGB(40, 38, 56),

	Stroke = Color3.fromRGB(65, 60, 94),
	FooterStroke = Color3.fromRGB(58, 53, 74),

	TooltipIcon = Color3.fromRGB(120, 120, 120),
	PrimaryText = Color3.fromRGB(195, 195, 195),
	SecondaryText = Color3.fromRGB(110, 110, 110),
	Header = Color3.fromRGB(249, 249, 249),

	Accent = Color3.fromRGB(0, 255, 159),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(19, 21, 24),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
