return {

	--Backgrounds
	WindowBackground = Color3.fromRGB(14, 13, 17),
	GroupboxBackground = Color3.fromRGB(17, 16, 21),
	ElementBackground = Color3.fromRGB(24, 23, 28),

	-- Outlines
	Stroke = Color3.fromRGB(58, 56, 68),
	FooterStroke = Color3.fromRGB(25, 24, 29),

	-- Texts
	TooltipIcon = Color3.fromRGB(113, 107, 134),
	PrimaryText = Color3.fromRGB(185, 184, 193),
	SecondaryText = Color3.fromRGB(102, 101, 108), -- placeholder text and subtitle
	Header = Color3.fromRGB(234, 233, 245),

	-- Misc
	Accent = Color3.fromRGB(159, 150, 193),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(19, 21, 24),

	-- States (misc colors meant for ping and fps in the watermark, but can be used in other purposes too)
	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
