return {
	WindowBackground = Color3.fromRGB(35, 42, 46),
	GroupboxBackground = Color3.fromRGB(45, 53, 59),
	ElementBackground = Color3.fromRGB(52, 63, 68),

	Stroke = Color3.fromRGB(79, 88, 94),
	FooterStroke = Color3.fromRGB(45, 53, 59),

	TooltipIcon = Color3.fromRGB(122, 132, 120),
	PrimaryText = Color3.fromRGB(157, 169, 160),
	SecondaryText = Color3.fromRGB(133, 146, 137),
	Header = Color3.fromRGB(211, 198, 170),

	Accent = Color3.fromRGB(167, 192, 128),
	Black = Color3.fromRGB(28, 36, 40),
	White = Color3.fromRGB(211, 198, 170),
	Shadow = Color3.fromRGB(28, 36, 40),

	Bad = Color3.fromRGB(230, 126, 128),
	Mid = Color3.fromRGB(219, 188, 127),
	Good = Color3.fromRGB(131, 192, 146),
}
