return {

	WindowBackground = Color3.fromRGB(25, 19, 53),
	GroupboxBackground = Color3.fromRGB(27, 22, 60),
	ElementBackground = Color3.fromRGB(35, 27, 68),

	Stroke = Color3.fromRGB(60, 53, 90),
	FooterStroke = Color3.fromRGB(40, 36, 54),

	TooltipIcon = Color3.fromRGB(140, 133, 165),
	PrimaryText = Color3.fromRGB(185, 184, 193),
	SecondaryText = Color3.fromRGB(102, 101, 108),
	Header = Color3.fromRGB(234, 233, 245),

	Accent = Color3.fromRGB(197, 7, 84),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(19, 21, 24),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
