return {

	WindowBackground = Color3.fromRGB(240, 238, 240),
	GroupboxBackground = Color3.fromRGB(244, 254, 255),
	ElementBackground = Color3.fromRGB(246, 250, 250),

	Stroke = Color3.fromRGB(190, 190, 190),
	FooterStroke = Color3.fromRGB(246, 255, 255),

	TooltipIcon = Color3.fromRGB(145, 145, 145),
	PrimaryText = Color3.fromRGB(40, 40, 40),
	SecondaryText = Color3.fromRGB(125, 125, 125),
	Header = Color3.fromRGB(10, 10, 10),

	Accent = Color3.fromRGB(255, 233, 192),
	Black = Color3.new(0, 0, 0),
	White = Color3.fromRGB(196, 222, 255),
	Shadow = Color3.fromRGB(164, 175, 179),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(255, 233, 192),
	Good = Color3.fromRGB(196, 222, 255),
}
