return {

	WindowBackground = Color3.fromRGB(26, 26, 26),
	GroupboxBackground = Color3.fromRGB(32, 32, 32),
	ElementBackground = Color3.fromRGB(34, 34, 34),

	Stroke = Color3.fromRGB(61, 61, 61),
	FooterStroke = Color3.fromRGB(34, 34, 34),

	TooltipIcon = Color3.fromRGB(85, 85, 85),
	PrimaryText = Color3.fromRGB(200, 200, 200),
	SecondaryText = Color3.fromRGB(122, 122, 122),
	Header = Color3.fromRGB(243, 243, 243),

	Accent = Color3.fromRGB(76, 194, 255),
	Black = Color3.fromRGB(13, 13, 13),
	White = Color3.fromRGB(243, 243, 243),
	Shadow = Color3.fromRGB(20, 20, 20),

	Bad = Color3.fromRGB(196, 43, 28),
	Mid = Color3.fromRGB(193, 156, 0),
	Good = Color3.fromRGB(15, 123, 15),
}
