return {

	WindowBackground = Color3.fromRGB(226, 225, 230),
	GroupboxBackground = Color3.fromRGB(216, 215, 221),
	ElementBackground = Color3.fromRGB(204, 203, 210),

	Stroke = Color3.fromRGB(168, 165, 180),
	FooterStroke = Color3.fromRGB(200, 198, 206),

	TooltipIcon = Color3.fromRGB(142, 139, 154),
	PrimaryText = Color3.fromRGB(59, 56, 69),
	SecondaryText = Color3.fromRGB(110, 108, 122),
	Header = Color3.fromRGB(26, 24, 32),

	Accent = Color3.fromRGB(124, 111, 160),
	Black = Color3.new(1, 1, 1),
	White = Color3.new(0, 0, 0),
	Shadow = Color3.fromRGB(19, 21, 24),

	Bad = Color3.fromRGB(192, 69, 58),
	Mid = Color3.fromRGB(176, 125, 42),
	Good = Color3.fromRGB(46, 143, 94),
}
