return {

	WindowBackground = Color3.fromRGB(21, 20, 25),
	GroupboxBackground = Color3.fromRGB(31, 30, 37),
	ElementBackground = Color3.fromRGB(37, 35, 44),

	Stroke = Color3.fromRGB(66, 63, 76),
	FooterStroke = Color3.fromRGB(43, 42, 49),

	TooltipIcon = Color3.fromRGB(116, 111, 134),
	PrimaryText = Color3.fromRGB(215, 215, 215),
	SecondaryText = Color3.fromRGB(97, 97, 97),
	Header = Color3.fromRGB(250, 250, 250),

	Accent = Color3.fromRGB(224, 138, 175),
	Black = Color3.new(0, 0, 0),
	White = Color3.fromRGB(123, 201, 201),
	Shadow = Color3.fromRGB(32, 28, 35),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
