return {

	WindowBackground = Color3.fromRGB(13, 17, 13),
	GroupboxBackground = Color3.fromRGB(16, 21, 16),
	ElementBackground = Color3.fromRGB(23, 28, 23),

	Stroke = Color3.fromRGB(56, 68, 58),
	FooterStroke = Color3.fromRGB(24, 29, 25),

	TooltipIcon = Color3.fromRGB(107, 134, 111),
	PrimaryText = Color3.fromRGB(184, 193, 185),
	SecondaryText = Color3.fromRGB(101, 108, 102),
	Header = Color3.fromRGB(233, 245, 235),

	Accent = Color3.fromRGB(129, 151, 114),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(19, 24, 19),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
