return {

	WindowBackground = Color3.fromRGB(14, 13, 17),
	GroupboxBackground = Color3.fromRGB(13, 17, 23),
	ElementBackground = Color3.fromRGB(14, 18, 26),

	Stroke = Color3.fromRGB(58, 56, 68),
	FooterStroke = Color3.fromRGB(25, 24, 29),

	TooltipIcon = Color3.fromRGB(111, 109, 117),
	PrimaryText = Color3.fromRGB(186, 194, 209),
	SecondaryText = Color3.fromRGB(100, 98, 105),
	Header = Color3.fromRGB(250, 250, 250),

	Accent = Color3.fromRGB(94, 255, 236),
	Black = Color3.new(0, 0, 0),
	White = Color3.fromRGB(172, 164, 255),
	Shadow = Color3.fromRGB(15, 15, 15),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
