return {

	WindowBackground = Color3.fromRGB(20, 20, 20),
	GroupboxBackground = Color3.fromRGB(24, 24, 24),
	ElementBackground = Color3.fromRGB(29, 29, 29),

	Stroke = Color3.fromRGB(63, 63, 63),
	FooterStroke = Color3.fromRGB(31, 31, 31),

	TooltipIcon = Color3.fromRGB(131, 131, 131),
	PrimaryText = Color3.fromRGB(197, 197, 197),
	SecondaryText = Color3.fromRGB(107, 107, 107),
	Header = Color3.fromRGB(247, 247, 247),

	Accent = Color3.fromRGB(231, 231, 231),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(17, 17, 17),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
