return {

	WindowBackground = Color3.fromRGB(45, 122, 80),
	GroupboxBackground = Color3.fromRGB(53, 138, 92),
	ElementBackground = Color3.fromRGB(62, 158, 106),

	Stroke = Color3.fromRGB(38, 112, 80),
	FooterStroke = Color3.fromRGB(45, 122, 80),

	TooltipIcon = Color3.fromRGB(74, 112, 85),
	PrimaryText = Color3.fromRGB(200, 240, 212),
	SecondaryText = Color3.fromRGB(122, 191, 148),
	Header = Color3.fromRGB(225, 255, 227),

	Accent = Color3.fromRGB(85, 255, 255),
	Black = Color3.fromRGB(14, 32, 24),
	White = Color3.fromRGB(225, 255, 227),
	Shadow = Color3.fromRGB(35, 102, 68),

	Bad = Color3.fromRGB(255, 107, 107),
	Mid = Color3.fromRGB(255, 208, 85),
	Good = Color3.fromRGB(85, 255, 127),
}
