return {

	WindowBackground = Color3.fromRGB(15, 15, 15),
	GroupboxBackground = Color3.fromRGB(24, 24, 24),
	ElementBackground = Color3.fromRGB(31, 31, 31),

	Stroke = Color3.fromRGB(43, 37, 42),
	FooterStroke = Color3.fromRGB(34, 26, 34),

	TooltipIcon = Color3.fromRGB(94, 74, 94),
	PrimaryText = Color3.fromRGB(199, 184, 200),
	SecondaryText = Color3.fromRGB(122, 106, 122),
	Header = Color3.fromRGB(254, 238, 255),

	Accent = Color3.fromRGB(224, 125, 67),
	Black = Color3.fromRGB(17, 12, 18),
	White = Color3.fromRGB(210, 101, 218),
	Shadow = Color3.fromRGB(26, 18, 24),

	Bad = Color3.fromRGB(224, 85, 96),
	Mid = Color3.fromRGB(255, 170, 68),
	Good = Color3.fromRGB(193, 61, 191),
}
