return {

	WindowBackground = Color3.fromRGB(23, 25, 29),
	GroupboxBackground = Color3.fromRGB(27, 29, 33),
	ElementBackground = Color3.fromRGB(33, 36, 42),

	Stroke = Color3.fromRGB(65, 69, 77),
	FooterStroke = Color3.fromRGB(33, 34, 38),

	TooltipIcon = Color3.fromRGB(85, 89, 97),
	PrimaryText = Color3.fromRGB(185, 185, 185),
	SecondaryText = Color3.fromRGB(165, 165, 165),
	Header = Color3.fromRGB(250, 250, 250),

	Accent = Color3.fromRGB(230, 186, 251),
	Black = Color3.new(0, 0, 0),
	White = Color3.fromRGB(138, 201, 242),
	Shadow = Color3.fromRGB(19, 21, 24),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(230, 186, 251),
	Good = Color3.fromRGB(138, 201, 242),
}
