return {

	WindowBackground = Color3.fromRGB(29, 27, 38),
	GroupboxBackground = Color3.fromRGB(35, 35, 48),
	ElementBackground = Color3.fromRGB(42, 41, 56),

	Stroke = Color3.fromRGB(70, 61, 82),
	FooterStroke = Color3.fromRGB(39, 35, 47),

	TooltipIcon = Color3.fromRGB(84, 82, 112),
	PrimaryText = Color3.fromRGB(184, 183, 216),
	SecondaryText = Color3.fromRGB(110, 109, 136),
	Header = Color3.fromRGB(221, 220, 245),

	Accent = Color3.fromRGB(103, 89, 179),
	Black = Color3.fromRGB(14, 12, 24),
	White = Color3.fromRGB(221, 220, 245),
	Shadow = Color3.fromRGB(22, 20, 32),

	Bad = Color3.fromRGB(196, 90, 106),
	Mid = Color3.fromRGB(196, 168, 74),
	Good = Color3.fromRGB(90, 158, 122),
}
