return {

	WindowBackground = Color3.fromRGB(34, 31, 28),
	GroupboxBackground = Color3.fromRGB(45, 42, 38),
	ElementBackground = Color3.fromRGB(53, 47, 43),

	Stroke = Color3.fromRGB(74, 68, 62),
	FooterStroke = Color3.fromRGB(53, 47, 43),

	TooltipIcon = Color3.fromRGB(158, 147, 120),
	PrimaryText = Color3.fromRGB(176, 169, 159),
	SecondaryText = Color3.fromRGB(151, 138, 105),
	Header = Color3.fromRGB(200, 195, 189),

	Accent = Color3.fromRGB(196, 149, 106),
	Black = Color3.new(0, 0, 0),
	White = Color3.new(1, 1, 1),
	Shadow = Color3.fromRGB(19, 21, 24),

	Bad = Color3.fromRGB(171, 94, 94),
	Mid = Color3.fromRGB(181, 138, 87),
	Good = Color3.fromRGB(86, 171, 128),
}
